#ifndef library_test_hooks_h
#define library_test_hooks_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#ifdef _WIN32
#define SHOREBIRD_EXPORT __declspec(dllexport)
#else
#define SHOREBIRD_EXPORT __attribute__((visibility("default")))
#endif


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Resets the updater's global config so the next `shorebird_init`
 * starts from scratch. Equivalent to a process restart for state
 * purposes — Dart tests call this between scenarios so each test
 * runs against a fresh updater.
 */
SHOREBIRD_EXPORT void shorebird_test_reset(void);

/**
 * Test-only convenience wrapper around `shorebird_init` that builds
 * `AppParameters` and stub `FileCallbacks` internally. Dart tests
 * pass plain C strings instead of needing bindings for those
 * engine-API structs.
 */
SHOREBIRD_EXPORT
bool shorebird_test_init(const char *app_storage_dir,
                         const char *code_cache_dir,
                         const char *release_version,
                         const char *libapp_path,
                         const char *yaml);

/**
 * Simulates the engine's successful boot of `next_boot_patch`.
 * In production this is two engine actions (launch-start, then
 * launch-success after Dart VM startup completes); the Dart layer
 * has no concept of either, so we expose the combined outcome as a
 * single semantic action: "the next patch booted cleanly."
 */
SHOREBIRD_EXPORT void shorebird_test_simulate_successful_launch(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* library_test_hooks_h */
