#ifndef library_test_hooks_h
#define library_test_hooks_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#ifdef _WIN32
#define SHOREBIRD_EXPORT __declspec(dllexport)
#else
#define SHOREBIRD_EXPORT __attribute__((visibility("default")))
#endif


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Resets the updater's global config so the next `shorebird_init`
 * starts from scratch. Equivalent to a process restart for state
 * purposes — Dart tests call this between scenarios so each test
 * runs against a fresh updater.
 */
SHOREBIRD_EXPORT void shorebird_test_reset(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* library_test_hooks_h */
