name: Rust Crate Workflow
description: Build and test your Rust crate

inputs:
  codecov_token:
    required: true
    description: The codecov token used to upload coverage reports.
  working_directory:
    required: false
    default: "."
    description: The working directory for this workflow.

runs:
  using: "composite"
  steps:
    - name: Build
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: cargo build --verbose

    - name: Test
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: |
        cargo install cargo-llvm-cov
        cargo llvm-cov --lcov --output-path lcov.info
    
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov_token }}
