# Not sure if .yaml suffix would work, currently using .yml to match examples:
# https://docs.codecov.com/docs/codecov-yaml
# Validate with:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
# See https://docs.codecov.com/docs/flags
flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    # We use Codecov's carryforward flags to allow our PR testing to only
    # run affected packages, but also allow our coverage information from
    # past runs to "carry forward" on a "per flag" basis.  We tag coverage
    # information with "flags" explaining what directory the coverage is from.
    # https://docs.codecov.com/docs/carryforward-flags
    carryforward: true
