# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/shorebird_code_push"
    schedule:
      interval: "weekly"
    groups:
      shorebird_code_push-deps:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/library"
    schedule:
      interval: "weekly"
    groups:
      library-deps:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/patch"
    schedule:
      interval: "weekly"
    groups:
      patch-deps:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-deps:
        patterns:
          - "*"
