name: updater_tools
description: Tools to create artifacts used by the Updater
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  archive: ^3.5.1
  args: ^2.4.2
  collection: ^1.18.0
  crypto: ^3.0.3
  mason_logger: ^0.2.12
  meta: ^1.15.0
  path: ^1.9.0
  process: ^5.0.2
  scoped_deps: ^0.1.0+1

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0

executables:
  updater_tools:
