name: Publish to pub.dev

on:
  push:
    tags:
    - 'shorebird_code_push-v[0-9]+.[0-9]+.[0-9]+*' # for tags like: 'v1.2.3'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/publish_flutter_package
      with:
       # Specify the github actions deployment environment
       working-directory: shorebird_code_push
